openapi: 3.2.0
info:
  title: Knowledge Collection Service API
  version: 1.0.0-alpha
tags:
- name: Knowledge Collection Service
paths:
  /api/knowledge/v1alpha1/collections/{collection_id}:
    get:
      tags:
      - Knowledge Collection Service
      summary: Retrieve Knowledge Collections
      description: Retrieve an existing knowledge collection.
      operationId: KnowledgeCollectionService_GetCollection
      parameters:
      - name: collection_id
        in: path
        description: Unique identifier of the knowledge collection.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCollectionResponse'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    GoogleProtobufAny:
      type: object
      properties:
        '@type':
          type: string
          description: The type of the serialized message.
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type
        of the serialized message.
    GetCollectionResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ResourceMetadata'
        data:
          $ref: '#/components/schemas/KnowledgeCollection'
    Status:
      type: object
      properties:
        code:
          type: integer
          description: The status code; enum value of google.rpc.Code.
          format: int32
        message:
          type: string
          description: Developer-facing error message.
        details:
          type: array
          items:
            $ref: '#/components/schemas/GoogleProtobufAny'
          description: List of messages that carry the error details.
      description: 'The `Status` type defines a logical error model that is suitable for different programming
        environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc).
        Each `Status` message contains three pieces of data: error code, error message, and error details.
        You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).'
    KnowledgeCollection:
      type: object
      properties:
        collection_id:
          type: string
          description: Unique identifier of the knowledge collection.
        active_domain_id:
          type: string
          description: Unique identifier of the current version domain.
        active_domain_history:
          type: array
          items:
            type: string
          description: All identifiers that were active throughout the life of the collection; autogenerated
            and listed in reverse order.
        team_ids:
          type: array
          items:
            type: string
          description: Unique identifiers of the teams authorized to the knowledge collection.
        solution_id:
          type: string
          description: Licensed solution for the collection; if not provided, the organizational default
            solution is automatically assigned.
      description: Versioned collection of documents accessible by authorized users.
    ResourceMetadata:
      type: object
      properties:
        uuid:
          type: string
          description: Unique identifier for the interaction returned in the resource response; the response
            ID.
        create_time:
          type: string
          description: Time of the initial request.
          format: date-time
        update_time:
          type: string
          description: Time of the last update; 0 indicates updates have never been made.
          format: date-time
        response_time_millis:
          type: integer
          description: Response time (in milliseconds).
          format: uint32
