openapi: 3.2.0
info:
  title: Knowledge Collection Service List Knowledge Collections API
  version: 1.0.0-alpha
tags:
- name: List Knowledge Collections
paths:
  /api/knowledge/v1alpha1/collections:
    get:
      tags:
      - List Knowledge Collections
      summary: List Knowledge Collections
      description: List all knowledge collections configured for an organization.
      operationId: KnowledgeCollectionService_ListCollections
      parameters:
      - name: team_id
        in: query
        description: Unique identifiers of the teams authorized to the knowledge collection.
        schema:
          type: string
      - name: page_size
        in: query
        description: Requested page size; default and maximum value are both 100.
        schema:
          type: integer
          format: int32
      - name: page_token
        in: query
        description: Returned for multiple pages; must be specified in each request for two pages per
          sheet using the page token parameter.
        schema:
          type: string
      - name: solution_id
        in: query
        description: Licensed solution for the collection; if not provided, the organizational default
          solution is automatically assigned.
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCollectionsResponse'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    CollectionMetadata:
      type: object
      properties:
        uuid:
          type: string
          description: Unique identifier for the interaction returned in the resource response; the response
            ID.
        response_time_millis:
          type: integer
          description: Response time (in milliseconds); latency.
          format: uint32
      description: Metadata returned with each collection-level GET.
    ListCollectionItem:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ResourceMetadata'
        data:
          $ref: '#/components/schemas/KnowledgeCollection'
    GoogleProtobufAny:
      type: object
      properties:
        '@type':
          type: string
          description: The type of the serialized message.
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type
        of the serialized message.
    ListCollectionsResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/CollectionMetadata'
        items:
          type: array
          items:
            $ref: '#/components/schemas/ListCollectionItem'
        next_page_token:
          type: string
          description: Returned for multiple pages; must be specified in each request for two pages per
            sheet using the page token parameter.
        total_size:
          type: integer
          description: Total number of items in the collection across all pages.
          format: int32
        page_size:
          type: integer
          description: Same as page size in request.
          format: int32
    Status:
      type: object
      properties:
        code:
          type: integer
          description: The status code; enum value of google.rpc.Code.
          format: int32
        message:
          type: string
          description: Developer-facing error message.
        details:
          type: array
          items:
            $ref: '#/components/schemas/GoogleProtobufAny'
          description: List of messages that carry the error details.
      description: 'The `Status` type defines a logical error model that is suitable for different programming
        environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc).
        Each `Status` message contains three pieces of data: error code, error message, and error details.
        You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).'
    KnowledgeCollection:
      type: object
      properties:
        collection_id:
          type: string
          description: Unique identifier of the knowledge collection.
        active_domain_id:
          type: string
          description: Unique identifier of the current version domain.
        active_domain_history:
          type: array
          items:
            type: string
          description: All identifiers that were active throughout the life of the collection; autogenerated
            and listed in reverse order.
        team_ids:
          type: array
          items:
            type: string
          description: Unique identifiers of the teams authorized to the knowledge collection.
        solution_id:
          type: string
          description: Licensed solution for the collection; if not provided, the organizational default
            solution is automatically assigned.
      description: Versioned collection of documents accessible by authorized users.
    ResourceMetadata:
      type: object
      properties:
        uuid:
          type: string
          description: Unique identifier for the interaction returned in the resource response; the response
            ID.
        create_time:
          type: string
          description: Time of the initial request.
          format: date-time
        update_time:
          type: string
          description: Time of the last update; 0 indicates updates have never been made.
          format: date-time
        response_time_millis:
          type: integer
          description: Response time (in milliseconds).
          format: uint32
